package(default_visibility = ["//visibility:public"])

java_library(
    name = "converters",
    srcs = glob(["*.java"]),
    deps = [
        "//java/net/ajmichael/classfile",
        "//java/net/ajmichael/javafile",
        "//third_party:auto_value",
        "//third_party:guava",
    ],
)
