package(default_visibility = ["//visibility:public"])

java_library(
    name = "classfile",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party:auto_value",
        "//third_party:guava",
    ],
)
